# Generated by Django 4.2.7 on 2024-04-16 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='item',
            name='rating',
            field=models.DecimalField(decimal_places=5, max_digits=5),
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ManyToManyField(to='store.category'),
        ),
    ]
