# Generated by Django 4.2.7 on 2024-04-17 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_item_image_alter_item_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='item',
            name='rating',
            field=models.CharField(max_length=5),
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.category'),
        ),
    ]
