# Generated by Django 4.2.7 on 2024-04-17 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_item_category_alter_item_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='tags',
        ),
        migrations.AddField(
            model_name='item',
            name='tags',
            field=models.ManyToManyField(db_index=True, null=True, to='store.tags'),
        ),
    ]
